# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Github Action Demo - Publish

on:
  push:
    branches: [ main ]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: asksmruti/gh-action
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
        with:
            email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
            api_key: ${{ secrets.HEROKU_API_KEY }} # your heroku api key
            app_name: 'gh-demo-app'
            dockerfile_path: '' # set the path to the folder where the Dockerfile is located
            options: '' # Docker Build Options
            formation: '' # Docker Dyno Formation. By default is web